// by ArT-iX

use cfgfile;

const cfgpath := ":Politics:territiories";

function GetTerritory(name)

 var cfgfile readconfigfile(cfgpath);
 return cfgfile[name];
 
endfunction

////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////


function CreateMultiTerritory(territories)
 foreach territory in territories
   
 endforeach
endfunction



