function getgumpdata(id)

var gump := {};
var layout;
var data;

case (id)

1:

      layout := {
                 "nodispose",
                 "page 0",
                 "gumppic 0 0 500",
                 "tilepic 80 75 2486",
                 "text 50 20 300 0",   
                 "text 40 115 0 1",
                 "text 40 140 0 2",
                 "text 40 165 0 3",
                
                 "text 230 60 0 4",
                 "text 275 190 0 5",
                 //"text 230 85 0 5",
                 //"text 230 110 0 6",
                 //"text 230 135 0 7",
                 //"text 230 160 0 8",
                 //"text 230 185 0 9",
                 "button 230 190 4020 4022 1 0 101"
                 };
                
      data := {"Fried Eggs",
               "Put a piece of butter",
               "and the eggs",
               "into a FryPan",
               "Then cook it.",
              
               "Cook it!"
               };


2:
    layout := {
                 "nodispose",
                 "page 0",
                 "gumppic 0 0 500",
                 "tilepic 80 75 5626",
                 "text 50 20 300 0",   
                 "text 40 115 0 1",
                 "text 40 140 0 2",
                 "text 40 165 0 3",
                
                 "text 230 60 0 4",
                 "text 275 190 0 8",
                 "text 230 85 0 5",
                 "text 230 110 0 6",
                 "text 230 135 0 7",
                 "text 230 160 0 8",
                 //"text 230 185 0 9",
                 "button 230 190 4020 4022 1 0 101"
                 };
                
      data := {"Corn Soup",
               "Put a dose of ",
               "corn flour",
               "into a kettle,",
               "a pot, or a ",
               "cauldron",
               "Put in a pitcher",
               "of water, and cook",
               "Cook it!"
               };
3:
  layout := {
                 "nodispose",
                 "page 0",
                 "gumppic 0 0 500",
                 "tilepic 80 75 2477",
                 "text 50 20 300 0",   
                 "text 40 115 0 1",
                 "text 40 140 0 2",
                 "text 40 165 0 3",
                
                 "text 230 60 0 4",
                 "text 275 190 0 7",
                 "text 230 85 0 5",
                 "text 230 110 0 6",
                 "text 230 135 0 7",
                 //"text 230 160 0 8",
                 //"text 230 185 0 9",
                 "button 230 190 4020 4022 1 0 101"
                 };
                
      data := {"Cream",
               "Put a pitcher of ",
               "milk, 2 eggs",
               "and a piece of",
               "butter into a",
               "cauldron or a ",
               "Pan, and cook it.",
               //"of water, and cook",
               "Cook it!"
               };

4:
      layout := {
                 "nodispose",
                 "page 0",
                 "gumppic 0 0 500",
                 "tilepic 80 75 5638",
                 "text 50 20 300 0",   
                 "text 40 115 0 1",
                 "text 40 140 0 2",
                 "text 40 165 0 3",
                
                 "text 230 60 0 4",
                 "text 275 190 0 7",
                 "text 230 85 0 5",
                 "text 230 110 0 6",
                 "text 230 135 0 7",
                 //"text 230 160 0 8",
                 //"text 230 185 0 9",
                 "button 230 190 4020 4022 1 0 101"
                 };
                
      data := {"Tomato Sauce",
               "Put a pitcher of ",
               "water with 10",
               "tomatoes",
               "into a cauldron,",
               "a pot or a ",
               "pan, and cook it.",
               //"of water, and cook",
               "Cook it!"
               };

5:
   layout := {
                 "nodispose",
                 "page 0",
                 "gumppic 0 0 500",
                 "tilepic 80 75 5628",
                 "text 50 20 300 0",   
                 "text 40 115 0 1",
                 "text 40 140 0 2",
                 "text 40 165 0 3",
                
                 "text 230 60 0 4",
                 "text 275 190 0 7",
                 "text 230 85 0 5",
                 "text 230 110 0 6",
                 "text 230 135 0 7",
                 //"text 230 160 0 8",
                 //"text 230 185 0 9",
                 "button 230 190 4020 4022 1 0 101"
                 };
                
      data := {"Boiled Cabbages",
               "Put a pitcher of ",
               "water and 2",
               "cabbages",
               "into a cauldron",
               "or a pot or a",
               "pan, and cook it.",
               //"of water, and cook",
               "Cook it!"
               };
6:

layout := {
                 "nodispose",
                 "page 0",
                 "gumppic 0 0 500",
                 "tilepic 80 75 5625",
                 "text 50 20 300 0",   
                 "text 40 115 0 1",
                 "text 40 140 0 2",
                 "text 40 165 0 3",
                
                 "text 230 60 0 4",
                 "text 275 190 0 7",
                 "text 230 85 0 5",
                 "text 230 110 0 6",
                 "text 230 135 0 7",
                 //"text 230 160 0 8",
                 //"text 230 185 0 9",
                 "button 230 190 4020 4022 1 0 101"
                 };
                
      data := {"Vegetarian Soup",
               "Put a pitcher of ",
               "water, 1 onion",
               "2 carrots, a ",
               "cabbage and a ",
               "pumpkin in a kettle",
               "or  a pan, and cook it.",
               //"of water, and cook",
               "Cook it!"
               };

7:
   layout := {
                 "nodispose",
                 "page 0",
                 "gumppic 0 0 500",
                 "tilepic 80 75 5625",
                 "text 50 20 300 0",   
                 "text 40 115 0 1",
                 "text 40 140 0 2",
                 "text 40 165 0 3",
                
                 "text 230 60 0 4",
                 "text 275 190 0 7",
                 "text 230 85 0 5",
                 "text 230 110 0 6",
                 "text 230 135 0 7",
                 //"text 230 160 0 8",
                 //"text 230 185 0 9",
                 "button 230 190 4020 4022 1 0 101"
                 };
                
      data := {"Fish Soup",
               "Put a pitcher of ",
               "water, 4 raw fish",
               "steaks, 2 shells,",
               "and a garlic",
               "in a cauldron or a ",
               "pan, and cook it.",
               //"of water, and cook",
               "Cook it!"
               };

endcase
gump := {layout, data};
return gump;
endfunction