var layouti := {
    "noclose",
    "nodispose",
     "page 0",
    "gumppic 0 0 500",
    "button 32 236 4020 4022 1 0 0",
    "text 60 20 300 0",
    "tilepic 80 50 6177",
    "text 50 100 0 1",
    "text 40 120 0 2",
    "text 40 140 0 3",
    "text 40 160 0 4",
    "text 40 180 0 5",
    "text 230 20 0 6",
    "text 230 40 0 7",
    "text 230 60 0 8",
    "text 230 80 0 9",
    "text 220 100 0 10",
    "button 230 190 4020 4022 1 0 101",
    "text 265 200 0 11",
    "tilepic 230 150 3960",  // reagents
    "text 265 150 0 12",
   
    "text 230 120 0 13",
    "tilepic 310 150 3971",
    "text 347 150 0 14",
    "text 40 200 0 15"
};



var datai := {
    "Blind Potion",
    "Codesta Pozione",
    "Se Colpisce gli Occhi",
    "Ruba ogni diurna luce",
    "e la vista getterà",
    "nelle Tenebre ",
    "Bollite in un calderone",
    "30 ali di Pipistrello,",
    "10 funghi del boia.",
    "Formule Magiche:",
    "An Lor,Taenebrae Noctis",
    "Create Potion",
    ":30",
    "An Lor",
    ":10",
    "della Notte!"
};

var layoutii := {
    "noclose",
    "nodispose",
     "page 0",
    "gumppic 0 0 500",
    "button 32 236 4020 4022 1 0 0",
    "text 60 20 300 0",
    "tilepic 80 50 3851",
    "text 50 110 0 1",
    "text 40 130 0 2",
    "text 40 150 0 3",
    "text 40 170 0 4",
    "text 40 190 0 5",
    "text 230 20 0 6",
    "text 230 40 0 7",
    "text 230 60 0 8",
    "text 230 80 0 9",
    "text 230 100 0 10",
    "button 230 190 4020 4022 1 0 101",
    "text 265 200 0 11",
    "tilepic 230 130 3851",
    "text 265 137 0 12",
    "tilepic 230 150 3974",
    "text 265 150 0 13",
    "tilepic 310 130 3965",
    "text 340 130 0 14"
};



var dataii := {
    "Fake Stamina",
    "Ingannevole pozione",
    "sembrerebbe aumentare",
    "le forze,ma in verità",
    "sfinisce colui che la ",
    "beve.",
    "Bollite in un calderone",
    "10 fiale ",
    "di pozioni rosse,",
    "30 di mandragola",
    "e 2 fiale di sangue.",
    "Create Potion",
    ":10",
    ":30",
    ":2"
};

var layoutiii := {
    "noclose",
    "nodispose",
     "page 0",
    "gumppic 0 0 500",
    "button 32 236 4020 4022 1 0 0",
    "text 60 20 300 0",
    "tilepic 80 50 3852",
    "text 50 110 0 1",
    "text 40 130 0 2",
    "text 40 150 0 3",
    "text 40 170 0 4",
    "text 40 190 0 5",
    "text 230 20 0 6",
    "text 230 40 0 7",
    "text 230 60 0 8",
    "text 230 80 0 9",
    "text 230 100 0 10",
    "button 230 190 4020 4022 1 0 101",
    "text 265 200 0 11",
    "tilepic 230 130 3852",
    "text 265 130 0 12",
    "tilepic 230 150 3965",
    "text 265 150 0 13",
    "tilepic 310 130 3962",
    "text 340 130 0 14"
};



var dataiii := {
    "Fake Heal",
    "Ingannevole, appare",
    "curativa, ma",
    "ferisce e reca danno",
    "ai mortali che ne",
    "faranno uso.",
    "Bollite in un calderone",
    "10fiale ",
    "di pozioni gialle,",
    "15 fiale di sangue",
    "e 35 Perle Nere.",
    "Create Potion",
    ":10",
    ":15",
    ":35"
};

var layoutiv := {
    "noclose",
    "nodispose",
     "page 0",
    "gumppic 0 0 500",
    "button 32 236 4020 4022 1 0 0",
    "text 60 20 300 0",
    "tilepic 80 50 6182",
    "text 50 110 0 1",
    "text 40 130 0 2",
    "text 40 150 0 3",
    "text 40 170 0 4",
    "text 40 190 0 5",
    "text 230 20 0 6",
    "text 230 40 0 7",
    "text 230 60 0 8",
    "text 230 80 0 9",
    "text 230 100 0 10",
    "button 230 190 4020 4022 1 0 101",
    "text 265 200 0 11",
    "tilepic 230 130 3853",
    "text 265 137 0 12",
    "tilepic 230 150 3980",
    "text 265 157 0 13",
    "tilepic 310 130 3983",
    "text 340 137 0 14"
};



var dataiv := {
    "Super Explosion",
    "Codesta pozione",
    "se lanciata a mo",
    "di dardo, Esplodera! ",
    "Bollite in un calderone",
    "20 fiale",
    "di pozioni esplosive,",
    "35 di cenere di zolfo ",
    "e 15 di cenere vulcanica",
    "Formule Magiche: :",
    "Hym Ra'sh Fe'Nor (1-3), In Corp Por",
    "Create Potion",
    ":20",
    ":35",
    ":15"
};

var layoutv := {
    "noclose",
    "nodispose",
     "page 0",
    "gumppic 0 0 500",
    "button 32 236 4020 4022 1 0 0",
    "text 60 20 300 0",
    "tilepic 80 50 8403",
    "text 50 110 0 1",
    "text 40 130 0 2",
    "text 40 150 0 3",
    "text 40 170 0 4",
    "text 40 190 0 5",
    "text 230 20 0 6",
    "text 230 40 0 7",
    "text 230 60 0 8",
    "text 230 80 0 9",
    "text 230 100 0 10",
    "button 230 190 4020 4022 1 0 101",
    "text 265 200 0 11",
    "tilepic 230 150 3960",
    "text 270 150 0 12",
    "tilepic 230 170 3968",
    "text 270 170 0 13",
    "tilepic 310 150 3965",
    "text 345 150 0 14",
    "tilepic 310 170 7401",
    "text 345 170 0 15", 
    "text 230 120 0 16"
};



var datav := {
    "Daemon Metamorph",
    "Codesta Pozione",
    "vi trasformerà in una",
    "creatura degli Inferi! ",
    "Bollite in un calderone",
    "20 ali di pipistrello",
    "35 di Ossa di Demone,",
    "15 fiale di sangue, ",
    "e una testa umana.",
  
    "Formule Magiche: ",
    "Hys Vor L'Dron Hel(1-3)",
    "Create Potion",
    ":10",
    ":15",
    ":25",
    ":1",
    "Ab Inferno"
};

var layoutvii := {
    "noclose",
    "nodispose",
     "page 0",
    "gumppic 0 0 500",
    "button 32 236 4020 4022 1 0 0",
    "text 60 20 300 0",
    "tilepic 80 50 8428",
    "text 50 110 0 1",
    "text 40 130 0 2",
    "text 40 150 0 3",
    "text 40 170 0 4",
    "text 40 190 0 5",
    "text 230 20 0 6",
    "text 230 40 0 7",
    "text 230 60 0 8",
    "text 230 80 0 9",
    "text 230 100 0 10",
    "button 230 190 4020 4022 1 0 101",
    "text 265 200 0 11",
    "tilepic 230 150 3960",
    "text 270 150 0 12",
    "tilepic 230 170 3968",
    "text 270 170 0 13",
    "tilepic 310 150 3965",
    "text 345 150 0 14",
    "tilepic 310 170 7401",
    "text 345 170 0 15", 
    "text 230 120 0 16"
};



var datavii := {
    "Undead",
    "Arcani Scritti",
    "insegnarono a ridar",
    "vita ai cadaveri! ",
    "Bollite in un calderone",
    "10pietra oscura",
    "15 di sangue secco,",
    "25 fiale di sangue, ",
    "e parti di cadavere.",
  
    "Formule Magiche: ",
    "Corp Myrh Tra'h(1-3)",
    "Create Potion",
    ":10",
    ":15",
    ":25",
    ":1",
    "Mortis Negatio"
};
