var layouti := {
    "noclose",
    "nodispose",
     "page 0",
    "gumppic 0 0 500",
    "button 32 236 4020 4022 1 0 0",
    "text 60 20 300 0",
    "tilepic 80 50 6175",
    "text 50 110 0 1",
    "text 40 130 0 2",
    "text 40 150 0 3",
    "text 40 170 0 4",
    "text 40 190 0 5",
    "text 230 20 0 6",
    "text 230 40 0 7",
    "text 230 60 0 8",
    "text 230 80 0 9",
    "text 230 100 0 10",
    "button 230 190 4020 4022 1 0 101",
    "text 265 200 0 11",
    "tilepic 230 130 3972",
    "text 265 130 0 12",
    "tilepic 230 150 3974",
    "text 265 150 0 13",
    "tilepic 310 130 3982",
    "text 340 130 0 14"
};



var datai := {
    "Total Heal",
    "Codesta pozione",
    "dai miracolosi effetti",
    "risanerà tutte le ferite",
    "dei mortali che ne",
    "faranno uso.",
    "Bollite in un calderone",
    "50 pezzi ",
    "di aglio garlico,",
    "50 di mandragola",
    "ed 1 scaglia di Serpe.",
    "Create Potion",
    ":50",
    ":50",
    ":1"
};

var layoutii := {
    "noclose",
    "nodispose",
     "page 0",
    "gumppic 0 0 500",
    "button 32 236 4020 4022 1 0 0",
    "text 60 20 300 0",
    "tilepic 80 50 6173",
    "text 50 110 0 1",
    "text 40 130 0 2",
    "text 40 150 0 3",
    "text 40 170 0 4",
    "text 40 190 0 5",
    "text 230 20 0 6",
    "text 230 40 0 7",
    "text 230 60 0 8",
    "text 230 80 0 9",
    "text 230 100 0 10",
    "button 230 190 4020 4022 1 0 101",
    "text 265 200 0 11",
    "tilepic 230 130 3972",
    "text 265 130 0 12",
    "tilepic 230 150 3973",
    "text 265 150 0 13",
    "tilepic 310 130 3970",
    "text 340 130 0 14"
};



var dataii := {
    "Protection",
    "Codesta pozione",
    "auemnta la resistenza",
    "alle ferite ",
    "dei mortali che ne",
    "faranno uso.",
    "Bollite in un calderone",
    "50 pezzi ",
    "di aglio garlico,",
    "40 di ginseng",
    "e sangue di drago.",
    "Create Potion",
    ":50",
    ":40",
    ":1"
};

var layoutiii := {
    "noclose",
    "nodispose",
     "page 0",
    "gumppic 0 0 500",
    "button 32 236 4020 4022 1 0 0",
    "text 60 20 300 0",
    "tilepic 80 50 6178",
    "text 50 110 0 1",
    "text 40 130 0 2",
    "text 40 150 0 3",
    "text 40 170 0 4",
    "text 40 190 0 5",
    "text 230 20 0 6",
    "text 230 40 0 7",
    "text 230 60 0 8",
    "text 230 80 0 9",
    "text 230 100 0 10",
    "button 230 190 4020 4022 1 0 101",
    "text 265 200 0 11",
    "tilepic 230 130 3972",
    "text 265 130 0 12",
    "tilepic 230 150 3974",
    "text 265 150 0 13",
    "tilepic 310 130 3985",
    "text 340 130 0 14"
};



var dataiii := {
    "Bless Potion",
    "Codesta pozione",
    "darà vigore, destrezza",
    "e forza spirituale",
    "ai mortali che ne",
    "faranno uso.",
    "Bollite in un calderone",
    "40 pezzi ",
    "di aglio garlico,",
    "35 di mandragola",
    "e 5 cuori di Dragone.",
    "Create Potion",
    ":40",
    ":35",
    ":1"
};

var layoutiv := {
    "noclose",
    "nodispose",
     "page 0",
    "gumppic 0 0 500",
    "button 32 236 4020 4022 1 0 0",
    "text 60 20 300 0",
    "tilepic 80 50 6182",
    "text 50 110 0 1",
    "text 40 130 0 2",
    "text 40 150 0 3",
    "text 40 170 0 4",
    "text 40 190 0 5",
    "text 230 20 0 6",
    "text 230 40 0 7",
    "text 230 60 0 8",
    "text 230 80 0 9",
    "text 230 100 0 10",
    "button 230 190 4020 4022 1 0 101",
    "text 265 200 0 11",
    "tilepic 230 130 3963",
    "text 265 130 0 12",
    "tilepic 230 150 3976",
    "text 265 150 0 13",
    "tilepic 310 130 3971",
    "text 340 130 0 14"
};



var dataiv := {
    "Invisibility",
    "Codesta pozione",
    "avrà il potere",
    "di rendervi invisibili",
    "Bollite in un calderone",
    "25 pezzi",
    "di muschio rosso,",
    "30 di OmbraDiNotte, ",
    "e 6 funghi del boia.",
    "e pronunciate 3 volte :",
    "Vas An Lor Xen",
    "Create Potion",
    ":25",
    ":30",
    ":6"
};

var layoutv := {
    "noclose",
    "nodispose",
     "page 0",
    "gumppic 0 0 500",
    "button 32 236 4020 4022 1 0 0",
    "text 60 20 300 0",
    "tilepic 80 50 6252",
    "text 50 110 0 1",
    "text 40 130 0 2",
    "text 40 150 0 3",
    "text 40 170 0 4",
    "text 40 190 0 5",
    "text 230 20 0 6",
    "text 230 40 0 7",
    "text 230 60 0 8",
    "text 230 80 0 9",
    "text 230 100 0 10",
    "button 230 190 4020 4022 1 0 101",
    "text 265 200 0 11",
    "tilepic 230 130 3977",
    "text 265 130 0 12",
    "tilepic 230 150 3982",
    "text 265 150 0 13",
    "tilepic 310 130 3967",
    "text 340 130 0 14"
};



var datav := {
    "Resurrection",
    "Codesta pozione",
    "restituirà la fiamma ",
    "vitale ai defunti.",
    "Bollite in un calderone",
    "15 pezzi",
    "di obsidian,",
    "35 squame di serpe , ",
    "e 15 BrimStones.",
    "e pronunciate 3 volte :",
    "An Corp",
    "Create Potion",
    ":15",
    ":35",
    ":15"
};

var layoutvi := {
    "noclose",
    "nodispose",
     "page 0",
    "gumppic 0 0 500",
    "button 32 236 4020 4022 1 0 0",
    "text 60 20 300 0",
    "tilepic 80 50 6252",
    "text 50 110 0 1",
    "text 40 130 0 2",
    "text 40 150 0 3",
    "text 40 170 0 4",
    "text 40 190 0 5",
    "text 230 20 0 6",
    "text 230 40 0 7",
    "text 230 60 0 8",
    "text 230 80 0 9",
    "text 230 100 0 10",
    "button 230 190 4020 4022 1 0 101",
    "text 265 200 0 11",
    "tilepic 230 130 3977",
    "text 265 130 0 12",
    "tilepic 230 150 3982",
    "text 265 150 0 13",
    "tilepic 310 130 3967",
    "text 340 130 0 14"
};



var datavi := {
    "Magic Resistance",
    "Codesta pozione",
    "donerà resistenza ",
    "a magiche offese",
    "Bollite in un calderone",
    "35 pezzi",
    "di obsidian,",
    "35 squame di serpe , ",
    "e 25 BrimStones.",
    "Formula Magica :",
    "D'hal por v'hyal",
    "Create Potion",
    ":35",
    ":35",
    ":25"
};

